### ISSUE TITLE
Get successful url

### ISSUE THREAD

**Issue by anujkumar-df** [EmilTholin/node-exchange-autodiscover#3]
A capability can be added to return the url/urls which were resolved.

**Comment by EmilTholin** [comment]
Hi anujkumaraurea! Sorry for not getting to you sooner.

I don't think this is something I would like to add to the project. Feel free to fork it and add it yourself.

**Comment by anujkumar-df** [comment]
Thanks, done that already :)

[image: Aurea] <http://www.aurea.com>

*Anuj Kumar* | C# Software Engineer

anuj.kumar@aurea.com | +919999490781

skype: anuj.kumar.aurea
<+919999490781>

www.aurea.com
